data_cfg:
  name: DrivingStereo
  root: /yourpath/DrivingStereo
  train_list: datasets/DrivingStereo/driving_stereo_train.txt
  val_list: datasets/DrivingStereo/driving_stereo_full_test.txt
  test_list: datasets/DrivingStereo/driving_stereo_full_test.txt
  num_workers: 0
  train_batch_size: 8
  val_batch_size: 1
  pin_memory: true
  shuffle: true
  return_right_disp: true
  batch_uniform: false

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: DivisiblePad
        by: 32
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: PSMNet

  base_config:
    max_disp: 192

  # Backbone
  backbone_cfg:
    type: PSMNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: PSMCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: PSMDispProcessor


loss_cfg:
  - log_prefix: disp
    loss_term_weight: 1
    type: Weighted_Smooth_l1_Loss
    weights: [ 0.5, 0.7, 1.0 ]


trainer_cfg:
  save_name: PSMNet_DrivingStereo
  total_epoch: 10
  restore_hint: /mnt/nas/public_data/.cache/openstereo_hub/PSMNet_Sceneflow.pt
  resume: false
  optimizer_reset: true
  scheduler_reset: true
  warmup_reset: true
  log_iter: 50 # iter
  save_every: 1 # epoch
  val_every: 1 # epoch
  amp: true
  sync_bn: true
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: RMSprop
    lr: 0.001

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.1
    milestones: [ 9 ]
    warmup:
      warmup_steps: 500

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - thres_1
      - thres_2
      - thres_3

  clip_grad_cfg:
    type: norm
    max_norm: 35
    norm_type: 2
