data_cfg:
  name: KITTI2015
  root: data/KITTI/kitti_stereo_2015
  train_list: datasets/KITTI15/kitti15_train200.txt
  val_list: datasets/KITTI15/kitti15_val35.txt
  test_list: datasets/KITTI15/kitti15_test.txt
  num_workers: 8
  train_batch_size: 4
  val_batch_size: 1
  pin_memory: true
  shuffle: true

  batch_uniform: true
  random_type: choice
  h_range: [ 256, 288, 320 ]
  w_range: [ 480, 512, 544 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    val:
      - type: CropOrPad
        size: [ 384, 1248 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: DivisiblePad
        by: 16
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: PSMNet

  base_config:
    max_disp: 192

  # Backbone
  backbone_cfg:
    type: PSMNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: PSMCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: PSMDispProcessor


loss_cfg:
  - log_prefix: disp
    loss_term_weight: 1
    type: Weighted_Smooth_l1_Loss
    weights: [ 0.5, 0.7, 1.0 ]


trainer_cfg:
  save_name: PSMNet_KITTI15
  total_epoch: 1000
  restore_hint: 'output/SceneFlow/PSMNet/PSMNet_SceneFlow/checkpoints/PSMNet_SceneFlow_epoch_015.pt'
  resume: false
  optimizer_reset: true
  scheduler_reset: true
  warmup_reset: true
  log_iter: 5 # iter
  save_every: 50 # epoch
  val_every: 10 # epoch
  amp: false
  sync_bn: true
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: RMSprop
    lr: 0.001

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.1
    milestones: [ 200 ]
    warmup:
      warmup_steps: 100

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - thres_1
      - thres_2
      - thres_3

  clip_grad_cfg:
    type: norm
    max_norm: 35
    norm_type: 2
