data_cfg:
  name: KITTI2012&2015
  root2012: data/kitti12
  root2015: data/kitti15
  train_list_2015: datasets/KITTI15/kitti15_train200.txt
  val_list_2015: datasets/KITTI15/kitti15_val35.txt
  test_list_2015: datasets/KITTI15/kitti15_test.txt
  train_list_2012: datasets/KITTI12/kitti12_train194.txt
  val_list_2012: datasets/KITTI12/kitti12_val29.txt
  test_list_2012: datasets/KITTI12/kitti12_test.txt
  num_workers: 4
  train_batch_size: 2
  val_batch_size: 1
  pin_memory: true
  shuffle: true
  test_on: 2015

  batch_uniform: false

  transform:
    train:
      - type: SparseFlowAugmentor
        size: [ 320, 736 ]
        min_scale: 0.2
        max_scale: 0.5
        do_flip: false
        h_flip_prob: 0.5
        v_flip_prob: 0.1

    val:
      - type: CropOrPad
        size: [ 384, 1248 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
    test:
      - type: DivisiblePad
        by: 32
      - type: TransposeImage
      - type: ToTensor

model_cfg:
  model: IGEV
  find_unused_parameters: true

  base_config:
    max_disp: 192
    hidden_dims: [ 128, 128, 128 ]
    n_gru_layers: 3
    n_downsample: 2
    slow_fast_gru: True
    corr_levels: 2
    corr_radius: 4
    train_iters: 22
    valid_iters: 32


loss_cfg:
  # This model uses the user-defined loss function.


trainer_cfg:
  save_name: igev_kitti
  total_epoch: 500
  restore_hint: "yourpath of sceneflow checkpoint"
  resume: false
  optimizer_reset: true
  scheduler_reset: true
  log_iter: 1 # iter
  save_every: 25 # epoch
  val_every: 25 # epoch
  amp: true
  sync_bn: true
  fix_bn: true
  init_parameters: false

  optimizer_cfg:
    solver: AdamW
    lr: 0.0002
    weight_decay: 0.00001
    eps: 0.00000001

  scheduler_cfg:
    scheduler: OneCycleLR
    max_lr: 0.0002
    total_steps: 12500
    pct_start: 0.01
    cycle_momentum: False
    anneal_strategy: linear
    on_epoch: false
#    warmup:
#      warmup_steps: 2000

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - bad_1
      - bad_2
      - bad_3

  clip_grad_cfg:
    type: value
    clip_value: 1.0
